; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ttgo-t1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = ttgo-t1
framework = arduino
board_build.partitions = min_spiffs.csv
board_build.filesystem = spiffs
lib_deps =
    zinggjm/GxEPD2
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson

monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
